Yechezkel/gadi backwards compatibility
chezi-nikop/hibob-academy pull request #17
Opened 2024-09-12 07:43 UTC by chezi-nikop

finish with compatibility

2024-09-15 12:49 UTC, brainpicker reviewed
Can you show an implementation where you handle the new extended `Owner`? Right now the way it's written I could potentially send an empty name, first name, last name and it would still be successful.

2024-09-19 05:51 UTC, omermelamed requested changes

2024-09-19 05:51 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/resource/OwnerResource.kt
> +            return Response.status(Response.Status.FORBIDDEN).entity("Name is required").build()
Forbidden or bad input?

2024-09-19 05:52 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/resource/OwnerResource.kt
> +            return Response.status(Response.Status.FORBIDDEN).entity("Name is required").build()
How can you create owner with owner?
Owner already have an id meaning it was already created

2024-10-31 08:29 UTC, closed without merging