Yechezkel/omer jooq
chezi-nikop/hibob-academy pull request #18
Opened 2024-09-12 18:01 UTC by chezi-nikop

finish with creating fun and tests for owner and pet

2024-09-13 07:34 UTC, omermelamed reviewed
Few comments.
You are missing a function that get the owner data by petId.
I didn't go over the tests yet.

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    }
Move to the Enum implementation, you can use this function in all over the system so it isnt smart to put it here.

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    }
Why not use !! ?

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    }
Do you think of a scenario when you query by null?
Moreover, add companyId here also.

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    fun  updateThePetOwnerWithTheOwnerId(petId: Long?, ownerId: Long) {
Im sure you can think of a better name for this function

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    fun  updateThePetOwnerWithTheOwnerId(petId: Long?, ownerId: Long) {
Same here, why nullable id?

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    fun  updateThePetOwnerWithTheOwnerId(petId: Long?, ownerId: Long) {
Add companyId as well in the where like all other functions in the dao.

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/models.kt
> +data class OwnerData(val name: String, val companyId: Long, val employeeId: String)
If pet holds ownerId so why doesnt owner holds id?

2024-09-13 07:34 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/tables.kt
> +    val ownerId = createBigIntField("owner_id")
Id should be the first column, ownerid is a reference for id in other table, please move it to be after the table id (petId in this case)

2024-09-13 07:34 UTC, omermelamed commented on src/main/resources/db/migration/V202409091400__create_pets_table.sql
> +    id BIGSERIAL primary key,
Please remove all migration code from this pr and put them in a different pr that contains only migrations.

2024-09-13 07:34 UTC, omermelamed commented on src/main/resources/db/migration/V202409091457__create_owner_table.sql
> +    company_id bigint not null,
Please remove all migration code from this pr and put them in a different pr that contains only migrations

2024-09-13 07:34 UTC, omermelamed commented on src/main/resources/db/migration/V202409091457__create_owner_table.sql
> +CREATE UNIQUE INDEX idx_owner_company_id_employee_id on Owner(company_id, employee_id);
Please remove all migration code from this pr and put them in a different pr that contains only migrations

2024-09-13 07:34 UTC, omermelamed commented on src/main/resources/db/migration/V202409111715__add_owner_to_pets_table.sql
> +
Please remove all migration code from this pr and put them in a different pr that contains only migrations

2024-09-13 07:34 UTC, omermelamed commented on src/main/resources/db/migration/V202409121600__make_company_id_bigint_on_pets_table.sql
> +ALTER COLUMN company_id TYPE BIGINT;
Please remove all migration code from this pr and put them in a different pr that contains only migrations

2024-09-14 04:11 UTC, omermelamed reviewed
Nice 👌🏻 you are missing a function that return OwnerData from petId and companyId.
Please add it and send me ti review.

2024-09-15 09:38 UTC, omermelamed requested changes

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +            .fetchOne()?.let { it[owner.ownerId] }
Why not !! ?

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +        val petsTable = PetsTable()
Please define the table at the beginning of the class

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +            .fetchOneInto(OwnerData::class.java)
Why not use the mapper?

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +            .fetchOneInto(PetData::class.java)
Why not use the mapper?

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/models.kt
> +data class PetData( val petId: Long, val ownerId: Long?, val name: String, val type: String, val companyId: Long, val dateOfArrival: LocalDate)
type should be from type PetType right?

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/models.kt
> +data class PetDataInsert(val ownerId: Long?, val name: String, val type: String, val companyId: Long)
Same

2024-09-15 09:38 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +            record[pet.type],
I think you should map the type to PetType type

2024-09-15 09:38 UTC, omermelamed commented on src/main/resources/db/migration/V202409091400__create_pets_table.sql
> +    id BIGSERIAL primary key,
Please remove migration code

2024-09-15 11:05 UTC, chezi-nikop commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +            .fetchOne()?.let { it[owner.ownerId] }
If there is already an owner I want it to return null

2024-09-16 07:06 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +            .fetchOne()?.let { it[owner.ownerId] }
Why not throw an exception?

2024-09-16 07:06 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +            .where(pet.type.eq(typeEnumToString(type)), pet.companyId.eq(companyId))
why not use .and here?

2024-09-16 07:06 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +            .where(petsTable.petId.eq(petId), petsTable.companyId.eq(companyId))
why not use .and here?

2024-09-16 07:06 UTC, omermelamed commented on src/main/kotlin/com/hibob/academy/dao/OwnerDao.kt
> +            .where(owner.ownerId.equal(id), owner.companyId.equal(companyId))
why not use .and here?

2024-09-16 07:09 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/OwnerDaoTest.kt
> +    }
Why not compare Owner to Owner?
try to compare the checkOwnerTest to a known Owner

2024-09-16 07:10 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/OwnerDaoTest.kt
> +        assertEquals(1, ownerDao.getAllOwners(companyId).size)
compare the returned list to a known list

2024-09-16 07:11 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/OwnerDaoTest.kt
> +        assertTrue(newOwner.employeeId.equals(ownerDao.getAllOwners(companyId)[0].employeeId))
Why not compare List<Owner> to List<Owner>?
try to compare the owners that returned from the function to a known Owners

2024-09-16 07:11 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/OwnerDaoTest.kt
> +        assertEquals(2, ownerDao.getAllOwners(companyId).size)
Why not compare List to List?
try to compare the owners that returned from the function to a known Owners

2024-09-16 07:12 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/PetsDaoTest.kt
> +        assertEquals(2, allPetsInData.size)
Why not compare List to List?
try to compare the pets that returned from the function to a known Pets

2024-09-16 07:12 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/PetsDaoTest.kt
> +        assertEquals(0, allPetsInData.size)
List.empty = allPetsInData is better

2024-09-16 07:12 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/PetsDaoTest.kt
> +        assertEquals(1, filteredPets.size)
Why not compare List to List?
try to compare the pets that returned from the function to a known Pets

2024-09-16 07:13 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/PetsDaoTest.kt
> +        assertEquals(petTest.companyId, petDao.getPet(newPetId, companyId)?.companyId)
Why not compare Pet to Pet?
try to compare the pet that returned from the function to a known Pet

2024-09-16 07:13 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/PetsDaoTest.kt
> +        assertEquals(ownerId, petDao.getPet(newPetId, companyId)?.ownerId)
Why not compare Pet to List?
try to compare the pet that returned from the function to a known Pet

2024-09-16 07:13 UTC, omermelamed commented on src/test/kotlin/com/hibob/academy/dao/PetsDaoTest.kt
> +        assertEquals(newOwnerId, petDao.getPet(newPetId, companyId)?.ownerId)
Why not compare Pet to Pet?
try to compare the pet that returned from the function to a known Pet

2024-09-16 14:18 UTC, elijulian commented on src/main/kotlin/com/hibob/academy/service/ExampleService.kt
@omermelamed ignore this file, this is related to fixes that @chezi-nikop and i needed to make to work out his github

2024-09-16 14:18 UTC, elijulian commented on src/main/kotlin/com/hibob/kotlinBasic/stringIsValid.kt
@omermelamed this one too

2024-09-17 07:35 UTC, chezi-nikop commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +        return sql.select(pet.ownerId, pet.petId, pet.name, pet.type, pet.companyId, pet.dateOfArrival)
Its Omer - you mixes between the ownerId and PetId

2024-09-17 07:36 UTC, chezi-nikop commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +        return sql.select(pet.ownerId, pet.petId, pet.name, pet.type, pet.companyId, pet.dateOfArrival)
same here

2024-09-17 07:38 UTC, chezi-nikop commented on src/main/kotlin/com/hibob/academy/dao/PetsDao.kt
> +    }
What does the id really mean here?

2024-09-17 10:35 UTC, omermelamed approved these changes

2024-09-17 14:13 UTC, merged